[workspace]
members = ["wqpl", "wq-cli", "wq-wasm", "wqls", "wq-dap", "wq-rl"]
resolver = "3"

[workspace.package]
version = "0.9.0-preview1"
edition = "2024"
license = "MIT"
repository = "https://codeberg.org/wqpl/wq"
description = "The wq Programming Language"
readme = "README.md"
publish = ["crates-io"]

[profile.R]
inherits = "release"
lto = "thin"
codegen-units = 1
strip = true

[workspace.dependencies]
ctrlc = "3.5.2"
rand = "0.10.2"
signal-hook = "0.4.4"
wqpl = { version = "0.9.0-preview1", path = "wqpl" }
wq-dap = { version = "0.9.0-preview1", path = "wq-dap" }
wq-rl = { version = "0.9.0-preview1", path = "wq-rl" }
