[package]
name = "wq-cli"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The wq Programming Language, CLI"
publish.workspace = true

[[bin]]
name = "wq"
path = "src/main.rs"

[dependencies]
rand.workspace = true
wqpl.workspace = true
wq-rl.workspace = true
pulldown-cmark = "0.13.4"
toml = "1.1.2"
clap = { version = "4", features = ["derive"] }
wq-dap.workspace = true
terminal_size = "0.4"
unicode-width = "0.2.2"

[dev-dependencies]
assert_cmd = "2"
anyhow = "1"
