[package]
name = "wq-cli"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for the wq Programming Language"
readme.workspace = true
publish.workspace = true

[[bin]]
name = "wq"
path = "src/main.rs"

[dependencies]
rand.workspace = true
wqpl.workspace = true
wq-rl.workspace = true
pulldown-cmark = "0.13.4"
toml = "1.1.2"
clap = { version = "4", features = ["derive"] }
wq-dap.workspace = true
terminal_size = "0.4"
unicode-width = "0.2.2"

[target.'cfg(unix)'.dependencies]
signal-hook.workspace = true

[target.'cfg(windows)'.dependencies]
ctrlc.workspace = true

[dev-dependencies]
assert_cmd = "2"
anyhow = "1"
