export const DEFAULT_STATE = {
  title: "Callable curves",
  layout: "below",
  mode: "line",
  complex: "re",
  theme: "none",
  axes: "full",
  grid: "4",
  palette: "classic",
  width: 90,
  widthAuto: true,
  height: 24,
  samples: 140,
  xlimMinText: "0",
  xlimMaxText: "6.283",
  ylimMinText: "",
  ylimMaxText: "",
  xlimLocked: false,
  ylimLocked: false,
  tableXText: "",
  tableYText: "",
  titleText: "sine and cosine",
  xlabelText: "x",
  ylabelText: "amplitude",
  labels: true,
  seriesOptions: true,
  unicode: true,
  autoRun: true,
  series: [
    { expr: "sin", label: "sin", symbol: "●", mode: "line" },
    { expr: "cos", label: "cos", symbol: "◆", mode: "line" },
  ],
};

export const PRESETS = {
  trig: {
    title: "Callable curves",
    mode: "line",
    complex: "re",
    theme: "maximal",
    axes: "full",
    grid: "4",
    palette: "classic",
    width: 90,
    height: 24,
    samples: 140,
    xlimMinText: "0",
    xlimMaxText: "6.283",
    ylimMinText: "",
    ylimMaxText: "",
    titleText: "sine and cosine",
    xlabelText: "x",
    ylabelText: "amplitude",
    unicode: true,
    series: [
      { expr: "sin", label: "sin", symbol: "●", mode: "line" },
      { expr: "cos", label: "cos", symbol: "◆", mode: "line" },
    ],
  },
  data: {
    title: "Sampled area",
    mode: "area",
    complex: "re",
    theme: "minimal",
    axes: "off",
    grid: "off",
    palette: "ink",
    width: 86,
    height: 18,
    samples: 80,
    xlimMinText: "",
    xlimMaxText: "",
    ylimMinText: "0",
    ylimMaxText: "12",
    titleText: "weekly activity",
    xlabelText: "sample",
    ylabelText: "events",
    unicode: true,
    series: [
      {
        expr: "(2;3;5;4;7;9;8;\n  10;7;6;8;11;9;5)",
        label: "activity",
        symbol: "░",
        mode: "area",
      },
    ],
    seriesOptions: false,
  },
  tablePlot: {
    title: "Column data",
    mode: "line",
    complex: "re",
    theme: "none",
    axes: "full",
    grid: "4",
    palette: "bright",
    width: 90,
    height: 22,
    samples: 80,
    xlimMinText: "0",
    xlimMaxText: "6",
    ylimMinText: "",
    ylimMaxText: "",
    tableXText: "x",
    tableYText: "observed;forecast",
    titleText: "observed and forecast",
    xlabelText: "day",
    ylabelText: "load",
    unicode: false,
    series: [
      {
        expr:
          "(`x:(0;1;2;3;4;5;6);\n  `observed:(2;4;5;4;7;8;7);\n  `forecast:(1;3;4;6;6;7;9))",
        label: "",
        symbol: "",
        mode: "",
      },
    ],
    seriesOptions: false,
  },
  cas: {
    title: "Symbolic curves",
    mode: "line",
    complex: "re",
    theme: "none",
    axes: "full",
    grid: "4",
    palette: "bright",
    width: 92,
    height: 24,
    samples: 170,
    xlimMinText: "-3",
    xlimMaxText: "3",
    ylimMinText: "-5",
    ylimMaxText: "5",
    titleText: "exact symbolic expressions",
    xlabelText: "x",
    ylabelText: "y",
    unicode: false,
    series: [
      { expr: "@s x^3-3*x", label: "cubic", symbol: "c", mode: "line" },
      {
        expr: "@s 1/(x^2+1)",
        label: "rational",
        symbol: "r",
        mode: "line",
      },
    ],
  },
  modes: {
    title: "Mixed modes",
    mode: "line",
    complex: "re",
    theme: "none",
    axes: "minimal",
    grid: "off",
    palette: "classic",
    width: 88,
    height: 20,
    samples: 80,
    xlimMinText: "",
    xlimMaxText: "",
    ylimMinText: "",
    ylimMaxText: "",
    titleText: "line, step, and scatter",
    xlabelText: "sample",
    ylabelText: "value",
    unicode: true,
    series: [
      {
        expr: "(1;2;3;5;4;6;7;6)",
        label: "trend",
        symbol: "─",
        mode: "line",
      },
      {
        expr: "(1;1;2;2;4;4;6;6)",
        label: "levels",
        symbol: "■",
        mode: "step",
      },
      {
        expr: "(2;3;2;4;5;5;8;7)",
        label: "samples",
        symbol: "●",
        mode: "scatter",
      },
    ],
  },
  bars: {
    title: "Category bars",
    mode: "bar",
    complex: "re",
    theme: "maximal",
    axes: "full",
    grid: "off",
    palette: "ink",
    width: 78,
    height: 18,
    samples: 80,
    xlimMinText: "",
    xlimMaxText: "",
    ylimMinText: "0",
    ylimMaxText: "12",
    titleText: "requests by category",
    xlabelText: "category",
    ylabelText: "requests",
    unicode: false,
    series: [
      {
        expr: "(3;8;5;11;7;9)",
        label: "requests",
        symbol: "#",
        mode: "bar",
      },
    ],
    seriesOptions: false,
  },
  complex: {
    title: "Complex plane",
    mode: "scatter",
    complex: "plane",
    theme: "minimal",
    axes: "off",
    grid: "off",
    palette: "classic",
    width: 90,
    height: 24,
    samples: 180,
    xlimMinText: "-8",
    xlimMaxText: "8",
    ylimMinText: "",
    ylimMaxText: "",
    titleText: "square root across the complex plane",
    xlabelText: "real",
    ylabelText: "imaginary",
    unicode: true,
    series: [{ expr: "sqrt", label: "sqrt", symbol: "●", mode: "scatter" }],
    seriesOptions: false,
  },
};
