mod cas;
mod core;
mod higher_order;
mod list;
mod listgen;
mod set;
mod string;

use super::super::model::BuiltinDoc;

pub(super) const BUILTIN_DOCS: &[BuiltinDoc] = &[
    core::BFN,
    core::CHR,
    core::ORD,
    core::INT,
    core::FLOAT,
    core::BIN,
    core::OCT,
    core::HEX,
    core::HASH,
    core::RAISE,
    core::ECHO,
    core::PRINT,
    core::INPUT,
    #[cfg(not(target_arch = "wasm32"))]
    core::EXEC,
    core::LEN,
    higher_order::APPLY,
    higher_order::MAP,
    higher_order::FOLD,
    higher_order::SCAN,
    higher_order::RSCAN,
    higher_order::ANY,
    higher_order::ALL,
    higher_order::FILTER,
    higher_order::ZIPW,
    higher_order::SPLITW,
    higher_order::FINDW,
    higher_order::RFINDW,
    list::SUM,
    list::PRODUCT,
    list::MIN,
    list::MAX,
    list::FLATTEN,
    list::REVERSE,
    list::SORT,
    list::SPLIT,
    list::FIND,
    list::RFIND,
    list::ZIP,
    listgen::ALLOC,
    listgen::TIL,
    listgen::IOTA,
    listgen::RESHAPE,
    listgen::TRANSPOSE,
    listgen::REPEAT,
    listgen::WHERE,
    set::UNIQUE,
    set::UNION,
    set::INTERSECT,
    set::WITHOUT,
    set::SYMDIFF,
    set::SUB_Q,
    set::SUPER_Q,
    set::P_SUB_Q,
    set::P_SUPER_Q,
    set::MEMBER_Q,
    set::CART,
    set::IN_Q,
    set::HAS_Q,
    set::DISJOINT_Q,
    set::MULTIPLICITY,
    string::STR,
    string::GRAPHEMES,
    string::WS_Q,
    string::WORDS,
    string::TRIM,
    string::L_TRIM,
    string::R_TRIM,
    string::FMT,
    cas::EQ,
    cas::SIMPLIFY,
    cas::REWRITE,
    cas::NUMERIC,
    cas::DIFF,
    cas::SUBSTITUTE,
    cas::EXPAND,
    cas::FACTOR_COMMON,
    cas::FACTOR,
    cas::INTEGRATE,
    cas::LIMIT,
    cas::SOLVE,
    cas::SOLVE_SYSTEM,
    cas::BRENT,
    cas::NEWTON,
];
