[package]
name = "wq-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The wq Programming Language for WebAssembly"
publish.workspace = true

[package.metadata.wasm-pack.profile.custom]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wqpl.workspace = true
getrandom03 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }
getrandom04 = { package = "getrandom", version = "0.4", features = ["wasm_js"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "console"] }
