[package]
name = "tree-sitter-wq"
description = "tree-sitter grammar for wq"
version = "0.8.0-b1"
authors = ["tttiw"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "wq"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://codeberg.org/wqpl/tree-sitter-wq"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.25.10"
