name: Build Binaries

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{ matrix.artifact_platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_platform: Linux
            executable_suffix: ""
          - os: windows-latest
            artifact_platform: Windows
            executable_suffix: .exe
          - os: macos-latest
            artifact_platform: macOS
            executable_suffix: ""

    steps:
      - uses: actions/checkout@v7

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binaries
        run: cargo build --locked --profile R --package wq-cli --package wqls

      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.artifact_platform }}
          path: |
            target/R/wq${{ matrix.executable_suffix }}
            target/R/wqls${{ matrix.executable_suffix }}
          if-no-files-found: error
